#!/usr/bin/env python3
"""
Generate MEM-ready state-vector text files and 3D orbit plots for circular or
elliptical orbits around inner Solar System bodies, Earth's Moon, or the Sun.

Default configuration:
- body: Mars
- orbit: circular
- altitude: 100 km
- inclination: 0 deg
- start epoch: 2033-01-01T00:00:00
- samples: 6

The output text file contains Julian date, position [km], and velocity [km/s]
for equally spaced time intervals over one orbital period.
"""
from __future__ import annotations

import argparse
import math
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np


@dataclass(frozen=True)
class Body:
    name: str
    radius_km: float
    mu_km3_s2: float
    color: str


BODY_DATA = {
    "mercury": Body("Mercury", 2439.7, 22031.86855, "dimgray"),
    "venus": Body("Venus", 6051.8, 324858.592, "#F4A460"),   # sandy yellow
    "earth": Body("Earth", 6378.137, 398600.4418, "royalblue"),
    "moon": Body("Moon", 1737.4, 4902.800066, "gray"),
    "mars": Body("Mars", 3389.5, 42828.375214, "orange"),
    "sun": Body("Sun", 695700.0, 132712440018.0, "yellow"),
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate MEM-ready orbit state vectors and a 3D orbit plot."
    )

    parser.add_argument("--body", default="mars", choices=sorted(BODY_DATA.keys()),
                        help="Central body. Default: mars")
    parser.add_argument("--orbit-type", default="circular", choices=["circular", "elliptical"],
                        help="Orbit type. Default: circular")

    # Simple circular-orbit inputs
    parser.add_argument("--altitude-km", type=float, default=5720.0,
                        help="Altitude above the reference radius for circular orbits [km]. Default: 100")
    parser.add_argument("--inclination-deg", type=float, default=20.0,
                        help="Inclination [deg]. Default: 0")

    # General orbital-element inputs
    parser.add_argument("--semi-major-axis-km", type=float, default=None,
                        help="Semi-major axis [km]. If omitted in circular mode, it is radius + altitude.")
    parser.add_argument("--eccentricity", type=float, default=None,
                        help="Eccentricity. Default is 0 for circular orbits.")
    parser.add_argument("--periapsis-altitude-km", type=float, default=None,
                        help="Periapsis altitude [km] for elliptical orbits.")
    parser.add_argument("--apoapsis-altitude-km", type=float, default=None,
                        help="Apoapsis altitude [km] for elliptical orbits.")
    parser.add_argument("--raan-deg", type=float, default=0.0,
                        help="Right ascension of ascending node [deg].")
    parser.add_argument("--arg-periapsis-deg", type=float, default=0.0,
                        help="Argument of periapsis [deg].")
    parser.add_argument("--true-anomaly-deg", type=float, default=0.0,
                        help="Initial true anomaly at the first sample [deg].")

    parser.add_argument("--num-points", type=int, default=6,
                        help="Number of sampled state vectors over one orbit. Default: 6")
    parser.add_argument("--start-date", default="2033-01-01T00:00:00",
                        help="UTC start date/time in ISO format. Default: 2033-01-01T00:00:00")
    parser.add_argument("--output-dir", default=r"C:\Users\maxiv\Documents\UWO\Papers\0.5)METEORCAM-Strawman\Test-Flux-surface\test-surf-mars",
                        help="Output directory. Default: current directory")
    parser.add_argument("--output-prefix", default=None,
                        help="Optional output filename prefix. Default: autogenerated")
    parser.add_argument("--full-orbit-points", type=int, default=600,
                        help="Number of points for drawing the orbit curve in the 3D plot. Default: 600")
    parser.add_argument("--view-elev-deg", type=float, default=25.0,
                        help="3D plot camera elevation [deg]. Default: 25")
    parser.add_argument("--view-azim-deg", type=float, default=-60.0,
                        help="3D plot camera azimuth [deg]. Default: -60")
    parser.add_argument("--body-alpha", type=float, default=0.55,
                        help="Planet/Sun sphere opacity from 0 to 1. Default: 0.55")
    parser.add_argument("--hide-point-numbers", action="store_true",
                        help="Hide the numeric labels beside the sampled state-vector points.")
    parser.add_argument("--point-number-offset-km", type=float, default=None,
                        help=("Radial offset of the numeric labels from their sampled points [km]. "
                              "Default: 2 percent of the central-body radius."))

    return parser.parse_args()


def datetime_to_julian_date(dt: datetime) -> float:
    """Convert a timezone-aware datetime to Julian Date."""
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    else:
        dt = dt.astimezone(timezone.utc)

    year = dt.year
    month = dt.month
    day = dt.day + (dt.hour + (dt.minute + (dt.second + dt.microsecond/1e6)/60.0)/60.0)/24.0

    if month <= 2:
        year -= 1
        month += 12

    A = math.floor(year/100)
    B = 2 - A + math.floor(A/4)

    jd = (math.floor(365.25*(year + 4716))
          + math.floor(30.6001*(month + 1))
          + day + B - 1524.5)
    return jd


def normalize_angle_rad(angle_rad: float) -> float:
    return float(np.mod(angle_rad, 2.0*np.pi))


def solve_kepler_equation(mean_anomaly_rad: np.ndarray, eccentricity: float,
                          tol: float = 1e-12, max_iter: int = 100) -> np.ndarray:
    """Solve M = E - e sin(E) for elliptical orbits."""
    M = np.asarray(mean_anomaly_rad, dtype=float)
    e = float(eccentricity)

    if e < 1e-14:
        return M.copy()

    E = M.copy()
    # improved initial guess
    E = np.where(e < 0.8, M, np.pi*np.ones_like(M))

    for _ in range(max_iter):
        f = E - e*np.sin(E) - M
        fp = 1.0 - e*np.cos(E)
        delta = -f/fp
        E = E + delta
        if np.all(np.abs(delta) < tol):
            break

    return E


def true_anomaly_to_eccentric_anomaly(true_anomaly_rad: float, eccentricity: float) -> float:
    e = float(eccentricity)
    nu = float(true_anomaly_rad)
    if e < 1e-14:
        return normalize_angle_rad(nu)

    tan_half_E = math.sqrt((1.0 - e)/(1.0 + e)) * math.tan(nu/2.0)
    E = 2.0*math.atan(tan_half_E)
    return normalize_angle_rad(E)


def rotation_matrix_313(raan_rad: float, inc_rad: float, argp_rad: float) -> np.ndarray:
    cO, sO = math.cos(raan_rad), math.sin(raan_rad)
    ci, si = math.cos(inc_rad), math.sin(inc_rad)
    co, so = math.cos(argp_rad), math.sin(argp_rad)

    return np.array([
        [cO*co - sO*so*ci, -cO*so - sO*co*ci, sO*si],
        [sO*co + cO*so*ci, -sO*so + cO*co*ci, -cO*si],
        [so*si, co*si, ci],
    ], dtype=float)


def state_vectors_from_elements(
    mu_km3_s2: float,
    semi_major_axis_km: float,
    eccentricity: float,
    inclination_deg: float,
    raan_deg: float,
    arg_periapsis_deg: float,
    true_anomaly_deg: float,
    time_offsets_s: Iterable[float],
) -> tuple[np.ndarray, np.ndarray]:
    """Generate inertial state vectors over time for a bound elliptic orbit."""
    mu = float(mu_km3_s2)
    a = float(semi_major_axis_km)
    e = float(eccentricity)

    if not (0.0 <= e < 1.0):
        raise ValueError("This script currently supports only circular/elliptical bound orbits with 0 <= e < 1.")
    if a <= 0.0:
        raise ValueError("Semi-major axis must be positive.")

    inc = math.radians(float(inclination_deg))
    raan = math.radians(float(raan_deg))
    argp = math.radians(float(arg_periapsis_deg))
    nu0 = math.radians(float(true_anomaly_deg))

    E0 = true_anomaly_to_eccentric_anomaly(nu0, e)
    M0 = E0 - e*math.sin(E0)

    n_rad_s = math.sqrt(mu/a**3)
    t = np.asarray(list(time_offsets_s), dtype=float)
    M = normalize_angle_rad(M0) + n_rad_s*t
    M = np.mod(M, 2.0*np.pi)
    E = solve_kepler_equation(M, e)

    cosE = np.cos(E)
    sinE = np.sin(E)
    r = a*(1.0 - e*cosE)
    p = a*(1.0 - e**2)

    nu = 2.0*np.arctan2(np.sqrt(1.0 + e)*np.sin(E/2.0), np.sqrt(1.0 - e)*np.cos(E/2.0))

    x_pqw = r*np.cos(nu)
    y_pqw = r*np.sin(nu)
    z_pqw = np.zeros_like(x_pqw)
    positions_pqw = np.vstack((x_pqw, y_pqw, z_pqw))

    sqrt_mu_over_p = math.sqrt(mu/p)
    vx_pqw = -sqrt_mu_over_p*np.sin(nu)
    vy_pqw = sqrt_mu_over_p*(e + np.cos(nu))
    vz_pqw = np.zeros_like(vx_pqw)
    velocities_pqw = np.vstack((vx_pqw, vy_pqw, vz_pqw))

    R = rotation_matrix_313(raan, inc, argp)
    positions_ijk = (R @ positions_pqw).T
    velocities_ijk = (R @ velocities_pqw).T
    return positions_ijk, velocities_ijk


def infer_orbit_parameters(args: argparse.Namespace, body: Body) -> tuple[float, float]:
    """Return semi-major axis [km] and eccentricity."""
    if args.orbit_type == "circular":
        e = 0.0 if args.eccentricity is None else float(args.eccentricity)
        if abs(e) > 1e-12:
            raise ValueError("Circular mode requires eccentricity = 0.")
        if args.semi_major_axis_km is not None:
            a = float(args.semi_major_axis_km)
        else:
            a = body.radius_km + float(args.altitude_km)
        return a, 0.0

    # Elliptical orbit
    if args.semi_major_axis_km is not None and args.eccentricity is not None:
        a = float(args.semi_major_axis_km)
        e = float(args.eccentricity)
        return a, e

    if args.periapsis_altitude_km is not None and args.apoapsis_altitude_km is not None:
        rp = body.radius_km + float(args.periapsis_altitude_km)
        ra = body.radius_km + float(args.apoapsis_altitude_km)
        a = 0.5*(rp + ra)
        e = (ra - rp)/(ra + rp)
        return a, e

    raise ValueError(
        "For elliptical mode, provide either --semi-major-axis-km with --eccentricity, "
        "or both --periapsis-altitude-km and --apoapsis-altitude-km."
    )


def orbital_period_seconds(mu_km3_s2: float, semi_major_axis_km: float) -> float:
    return 2.0*np.pi*np.sqrt(semi_major_axis_km**3/float(mu_km3_s2))


def write_mem_file(
    output_path: Path,
    body: Body,
    orbit_type: str,
    semi_major_axis_km: float,
    eccentricity: float,
    inclination_deg: float,
    samples_jd: np.ndarray,
    positions_km: np.ndarray,
    velocities_km_s: np.ndarray,
) -> None:
    lines = [
        "# MEM state-vector file generated by mem_orbit_generator.py",
        f"# Central body: {body.name}",
        f"# Orbit type: {orbit_type}; a = {semi_major_axis_km:.6f} km; e = {eccentricity:.8f}; i = {inclination_deg:.6f} deg",
        f"# Reference radius: {body.radius_km:.6f} km; mu = {body.mu_km3_s2:.9f} km^3/s^2",
        f"# For MEM choose input origin = {body.name} and input axes = equatorial",
        "# JD x(km) y(km) z(km) vx(km/s) vy(km/s) vz(km/s)",
    ]

    with output_path.open("w", encoding="utf-8", newline="\n") as f:
        for line in lines:
            f.write(line + "\n")
        for jd, r_vec, v_vec in zip(samples_jd, positions_km, velocities_km_s):
            f.write(
                f"{jd:.8f} "
                f"{r_vec[0]:.6f} {r_vec[1]:.6f} {r_vec[2]:.6f} "
                f"{v_vec[0]:.9f} {v_vec[1]:.9f} {v_vec[2]:.9f}\n"
            )


def set_axes_equal(ax: plt.Axes, x: np.ndarray, y: np.ndarray, z: np.ndarray) -> None:
    x_min, x_max = np.nanmin(x), np.nanmax(x)
    y_min, y_max = np.nanmin(y), np.nanmax(y)
    z_min, z_max = np.nanmin(z), np.nanmax(z)

    x_range = x_max - x_min
    y_range = y_max - y_min
    z_range = z_max - z_min
    max_range = max(x_range, y_range, z_range)

    x_mid = 0.5*(x_max + x_min)
    y_mid = 0.5*(y_max + y_min)
    z_mid = 0.5*(z_max + z_min)

    half = 0.55*max_range
    if half <= 0:
        half = 1.0

    ax.set_xlim(x_mid - half, x_mid + half)
    ax.set_ylim(y_mid - half, y_mid + half)
    ax.set_zlim(z_mid - half, z_mid + half)
    ax.set_box_aspect((1, 1, 1))


def camera_direction_from_view(elevation_deg: float, azimuth_deg: float) -> np.ndarray:
    """Return the unit vector from the origin toward the Matplotlib 3D camera."""
    elev = math.radians(float(elevation_deg))
    azim = math.radians(float(azimuth_deg))
    direction = np.array([
        math.cos(elev)*math.cos(azim),
        math.cos(elev)*math.sin(azim),
        math.sin(elev),
    ], dtype=float)
    return direction/np.linalg.norm(direction)


def front_side_mask(positions_km: np.ndarray, camera_direction: np.ndarray) -> np.ndarray:
    """Classify points as front-side when they lie toward the viewing camera."""
    positions = np.asarray(positions_km, dtype=float)
    return (positions @ np.asarray(camera_direction, dtype=float)) >= 0.0


def plot_masked_closed_orbit(
    ax: plt.Axes,
    positions_km: np.ndarray,
    mask: np.ndarray,
    *,
    color: str,
    linewidth: float,
    alpha: float,
    zorder: float,
    label: str | None = None,
) -> None:
    """Plot only selected contiguous portions of a closed orbit without false joins."""
    positions = np.asarray(positions_km, dtype=float)
    selected = np.asarray(mask, dtype=bool)
    if positions.ndim != 2 or positions.shape[1] != 3:
        raise ValueError("Orbit positions must have shape (N, 3).")
    if len(positions) != len(selected):
        raise ValueError("Orbit mask length does not match the orbit positions.")

    # Close the curve, then use NaNs to break the line wherever this side is hidden.
    closed_positions = np.vstack((positions, positions[0]))
    closed_mask = np.concatenate((selected, selected[:1]))
    displayed = closed_positions.copy()
    displayed[~closed_mask] = np.nan

    ax.plot(
        displayed[:, 0], displayed[:, 1], displayed[:, 2],
        color=color,
        lw=float(linewidth),
        alpha=float(alpha),
        zorder=float(zorder),
        label=label,
    )


def save_3d_orbit_plot(
    output_path: Path,
    body: Body,
    orbit_positions_km: np.ndarray,
    sample_positions_km: np.ndarray,
    title: str,
    view_elev_deg: float = 25.0,
    view_azim_deg: float = -60.0,
    body_alpha: float = 0.55,
    show_point_numbers: bool = True,
    point_number_offset_km: float | None = None,
) -> None:
    """
    Draw a translucent central body with the orbit correctly wrapping around it.

    The orbit and sampled points are split into back-side and front-side groups
    relative to the selected view. Back-side objects are drawn first, followed
    by the translucent body, and then the front-side objects. This avoids the
    common mplot3d appearance where the whole orbit is either in front of or
    behind the planet.
    """
    fig = plt.figure(figsize=(10, 8))
    ax = fig.add_subplot(111, projection="3d", computed_zorder=False)
    ax.view_init(elev=float(view_elev_deg), azim=float(view_azim_deg))

    orbit_positions_km = np.asarray(orbit_positions_km, dtype=float)
    sample_positions_km = np.asarray(sample_positions_km, dtype=float)
    camera_direction = camera_direction_from_view(view_elev_deg, view_azim_deg)

    orbit_front = front_side_mask(orbit_positions_km, camera_direction)
    orbit_back = ~orbit_front
    sample_front = front_side_mask(sample_positions_km, camera_direction)
    sample_back = ~sample_front

    # Point numbers correspond directly to the data-line order in the MEM text file:
    # point 1 is the first state-vector row, point 2 is the second row, and so on.
    point_numbers = np.arange(1, len(sample_positions_km) + 1, dtype=int)
    if point_number_offset_km is None:
        point_number_offset_km = 0.02*float(body.radius_km)
    point_number_offset_km = max(0.0, float(point_number_offset_km))

    sample_radii = np.linalg.norm(sample_positions_km, axis=1)
    radial_units = np.zeros_like(sample_positions_km)
    valid_radii = sample_radii > 0.0
    radial_units[valid_radii] = (
        sample_positions_km[valid_radii]/sample_radii[valid_radii, None]
    )
    label_positions_km = (
        sample_positions_km + point_number_offset_km*radial_units
    )

    # Draw the portions behind the body first. They remain faintly visible
    # through the translucent sphere.
    plot_masked_closed_orbit(
        ax,
        orbit_positions_km,
        orbit_back,
        color="green",
        linewidth=2.0,
        alpha=0.32,
        zorder=1,
        # label="Orbit behind body",
    )
    if np.any(sample_back):
        ax.scatter(
            sample_positions_km[sample_back, 0],
            sample_positions_km[sample_back, 1],
            sample_positions_km[sample_back, 2],
            color="red",
            s=46,
            alpha=0.35,
            depthshade=False,
            zorder=1.2,
            # label="Sampled points behind body",
        )

    if show_point_numbers:
        for point_index in np.flatnonzero(sample_back):
            x_label, y_label, z_label = label_positions_km[point_index]
            ax.text(
                x_label,
                y_label,
                z_label,
                str(point_numbers[point_index]),
                color="darkred",
                fontsize=9,
                fontweight="bold",
                ha="center",
                va="center",
                alpha=0.38,
                zorder=1.4,
                bbox={
                    "boxstyle": "circle,pad=0.16",
                    "facecolor": "white",
                    "edgecolor": "red",
                    "linewidth": 0.7,
                    "alpha": 0.35,
                },
            )

    # Draw the body between the back and front portions.
    R = body.radius_km
    u = np.linspace(0, 2*np.pi, 100)
    v = np.linspace(0, np.pi, 60)
    xs = R*np.outer(np.cos(u), np.sin(v))
    ys = R*np.outer(np.sin(u), np.sin(v))
    zs = R*np.outer(np.ones_like(u), np.cos(v))
    ax.plot_surface(
        xs,
        ys,
        zs,
        color=body.color,
        alpha=float(np.clip(body_alpha, 0.0, 1.0)),
        linewidth=0,
        shade=True,
        antialiased=True,
        zorder=2,
    )

    # Draw the portions toward the camera after the sphere.
    plot_masked_closed_orbit(
        ax,
        orbit_positions_km,
        orbit_front,
        color="green",
        linewidth=2.5,
        alpha=1.0,
        zorder=3,
        label="Orbit",
    )
    if np.any(sample_front):
        ax.scatter(
            sample_positions_km[sample_front, 0],
            sample_positions_km[sample_front, 1],
            sample_positions_km[sample_front, 2],
            color="red",
            s=55,
            alpha=1.0,
            depthshade=False,
            zorder=4,
            label="Sampled points (numbered)",
        )

    if show_point_numbers:
        for point_index in np.flatnonzero(sample_front):
            x_label, y_label, z_label = label_positions_km[point_index]
            ax.text(
                x_label,
                y_label,
                z_label,
                str(point_numbers[point_index]),
                color="darkred",
                fontsize=9,
                fontweight="bold",
                ha="center",
                va="center",
                alpha=1.0,
                zorder=4.5,
                bbox={
                    "boxstyle": "circle,pad=0.16",
                    "facecolor": "white",
                    "edgecolor": "red",
                    "linewidth": 0.8,
                    "alpha": 0.82,
                },
            )

    # # Mark the initial point with the same front/back ordering.
    # start_is_front = bool(sample_front[0])
    # ax.scatter(
    #     [sample_positions_km[0, 0]],
    #     [sample_positions_km[0, 1]],
    #     [sample_positions_km[0, 2]],
    #     color="red",
    #     s=100,
    #     marker="*",
    #     alpha=1.0 if start_is_front else 0.40,
    #     depthshade=False,
    #     zorder=4.5 if start_is_front else 1.4,
    #     label="Start point",
    # )

    all_x = np.concatenate([orbit_positions_km[:, 0], [R, -R]])
    all_y = np.concatenate([orbit_positions_km[:, 1], [R, -R]])
    all_z = np.concatenate([orbit_positions_km[:, 2], [R, -R]])
    set_axes_equal(ax, all_x, all_y, all_z)

    ax.set_xlabel("X [km]")
    ax.set_ylabel("Y [km]")
    ax.set_zlabel("Z [km]")
    ax.set_title(title)
    ax.legend(loc="upper right", fontsize=9)
    ax.grid(True, alpha=0.3)
    plt.tight_layout()
    fig.savefig(output_path, dpi=300)
    plt.close(fig)


def main() -> None:
    args = parse_args()
    body = BODY_DATA[args.body.lower()]
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    start_dt = datetime.fromisoformat(args.start_date)
    if start_dt.tzinfo is None:
        start_dt = start_dt.replace(tzinfo=timezone.utc)
    jd0 = datetime_to_julian_date(start_dt)

    a_km, e = infer_orbit_parameters(args, body)
    if a_km <= body.radius_km:
        raise ValueError("Semi-major axis must be larger than the body radius.")

    period_s = orbital_period_seconds(body.mu_km3_s2, a_km)

    n_samples = int(args.num_points)
    if n_samples < 1:
        raise ValueError("--num-points must be >= 1")
    sample_times_s = np.linspace(0.0, period_s, n_samples, endpoint=False)

    sample_positions, sample_velocities = state_vectors_from_elements(
        mu_km3_s2=body.mu_km3_s2,
        semi_major_axis_km=a_km,
        eccentricity=e,
        inclination_deg=args.inclination_deg,
        raan_deg=args.raan_deg,
        arg_periapsis_deg=args.arg_periapsis_deg,
        true_anomaly_deg=args.true_anomaly_deg,
        time_offsets_s=sample_times_s,
    )
    sample_jd = jd0 + sample_times_s/86400.0

    dense_times_s = np.linspace(0.0, period_s, int(args.full_orbit_points), endpoint=False)
    orbit_positions, _ = state_vectors_from_elements(
        mu_km3_s2=body.mu_km3_s2,
        semi_major_axis_km=a_km,
        eccentricity=e,
        inclination_deg=args.inclination_deg,
        raan_deg=args.raan_deg,
        arg_periapsis_deg=args.arg_periapsis_deg,
        true_anomaly_deg=args.true_anomaly_deg,
        time_offsets_s=dense_times_s,
    )

    if args.output_prefix is None:
        prefix = f"MEM_{body.name.lower()}_{args.orbit_type}"
    else:
        prefix = args.output_prefix

    txt_path = output_dir / f"{prefix}_state_vectors.txt"
    png_path = output_dir / f"{prefix}_orbit_3d.png"

    write_mem_file(
        output_path=txt_path,
        body=body,
        orbit_type=args.orbit_type,
        semi_major_axis_km=a_km,
        eccentricity=e,
        inclination_deg=args.inclination_deg,
        samples_jd=sample_jd,
        positions_km=sample_positions,
        velocities_km_s=sample_velocities,
    )

    if args.orbit_type == "circular":
        orbit_desc = f"alt = {a_km - body.radius_km:.1f} km, i = {args.inclination_deg:.1f}°"
    else:
        rp = a_km*(1.0 - e)
        ra = a_km*(1.0 + e)
        orbit_desc = (
            f"rp alt = {rp - body.radius_km:.1f} km, "
            f"ra alt = {ra - body.radius_km:.1f} km, i = {args.inclination_deg:.1f}°"
        )

    title = f"{body.name} {args.orbit_type.capitalize()} orbit\n{orbit_desc}"
    save_3d_orbit_plot(
        output_path=png_path,
        body=body,
        orbit_positions_km=orbit_positions,
        sample_positions_km=sample_positions,
        title=title,
        view_elev_deg=args.view_elev_deg,
        view_azim_deg=args.view_azim_deg,
        body_alpha=args.body_alpha,
        show_point_numbers=not args.hide_point_numbers,
        point_number_offset_km=args.point_number_offset_km,
    )

    print(f"Created MEM state-vector file: {txt_path}")
    print(f"Created orbit plot: {png_path}")
    print(f"Start Julian date: {jd0:.8f}")
    print(f"Orbital period: {period_s:.3f} s")
    print(f"Samples: {n_samples}")


if __name__ == "__main__":
    main()